import AllGames from "@/components/adminComp/AllGames";

export const metadata = {
  title: "Admin - Games",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div>
      <AllGames />
    </div>
  );
};

export default Page;
